name: PersonalViewDistance
version: 1.1.0
api-version: 1.13
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
main: com.karlofduty.personalviewdistance.PersonalViewDistance
permissions:
  viewdistance.*:
    description: Lets a player use all render distances supported.
    default: op
  viewdistance.x:
    description: Lets a player use a specific view distance.
    default: false
  viewdistance.autodistance:
    description: Sets a player's viewdistance to the highest one they have access to.
    default: false
commands:
  viewdistance:
    description: Changes the player's view distance.
    usage: /viewdistance <range>